services:
  dockerlock:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: josedmyt/heart-disease-predictor@sha256:2adf5d2b48a3427b5fb543b0772f0d071bb2a9acbecb1fa27735faea9ce171bb
    container_name: heart-disease-predictor
    ports:
      - "8899:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true