Last login: Wed Nov 19 14:58:38 on ttys000

(base) azadeh@s-MacBook-Air ~
$ cd /Users/azadeh/Documents/UBCMDS/DSCI_522_Data_Science_Workflows/

(base) azadeh@s-MacBook-Air ~/Documents/UBCMDS/DSCI_522_Data_Science_Workflows
$ 

(base) azadeh@s-MacBook-Air ~/Documents/UBCMDS/DSCI_522_Data_Science_Workflows
$ git clone https://github.com/stoyq/cov-hydrants-installation-trend.git
Cloning into 'cov-hydrants-installation-trend'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 5 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 493.09 KiB | 1.31 MiB/s, done.
Resolving deltas: 100% (1/1), done.

(base) azadeh@s-MacBook-Air ~/Documents/UBCMDS/DSCI_522_Data_Science_Workflows
$ ls
Cheatsheet                      Lectures
cov-hydrants-installation-trend Project1
learning-about-version-control  Solution

(base) azadeh@s-MacBook-Air ~/Documents/UBCMDS/DSCI_522_Data_Science_Workflows
$ cd cov-hydrants-installation-trend

(base) azadeh@s-MacBook-Air ~/Documents/UBCMDS/DSCI_522_Data_Science_Workflows/cov-hydrants-installation-trend (main)
$ conda-lock -f environment.yml
-bash: conda-lock: command not found

(base) azadeh@s-MacBook-Air ~/Documents/UBCMDS/DSCI_522_Data_Science_Workflows/cov-hydrants-installation-trend (main)
$ nano environment.yml











  UW PICO 5.09                 File: environment.yml                  Modified  

name: hydrant-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - pip































^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Pg   ^K Cut Text  ^C Cur Pos   
^X Exit      ^J Justify   ^W Where is  ^V Next Pg   ^U UnCut Text^T To Spell  
