name: group25-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.1.4
  - numpy=1.26.4
  - matplotlib=3.10
  - seaborn=0.13.2
  - scikit-learn=1.3.2
  - requests=2.32.5
  - jupyterlab=4.5.0
  - ucimlrepo=0.0.7
  - conda-lock=3.0.4
  - pandera=0.27.0
  - pip=25.3
  - deepchecks
  - ipython<9
  - pointblank=0.16.0