name: group25-env
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - requests
  - jupyterlab
  - ucimlrepo
  - conda-lock
  - pip
  - pip:
      - ucimlrepo
      - deepchecks
      - pointblank
